# The URL the site will be built for
base_url = "https://rynn.netlify.app/"

# Used in RSS by default
title = "Rinfela's blog"
description = "Phur hluai thil tih ve mai mai!"

# The default language, used in RSS
default_language = "en"

# Whether to generate a RSS feed automatically
# generate_feeds = true
# feed_filenames = ["atom.xml"]

# Theme name to use.
theme = "zerm"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Built in taxonomies of zerm.
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[markdown]
highlight_code = true
highlight_theme = "axar" 
# Other dark themes that work: "1337", "agola-dark","visual-studio-dark"

[slugify]
paths = "on"
taxonomies = "on"
achors = "on"

[extra]
# Put all your custom variables here

# Author name to be added to posts, if enabled.
author = "Rinfela Pachuau"

# Show author's name in blog post meta data.
show_author = false

# Show categories a blog post is marked with in its meta data.
show_categories = true

# Show tags a blog post is marked with in its meta data.
show_tags = true

# Theme color. You can have any color you want, so long as it's...
# ["orange", "blue", "red", "green", "pink"]
theme_color = "blue"

# How many menu items to show on desktop. if you set this to 0, only submenu
# button will be visible.
show_menu_items = 6

# set theme to full screen width.
full_width = false

# center theme with default width.
center = true

# favicon = ""


# Set a custom preview image for your website when posted as a link.
# Must be placed in root of static/ directory...
# og_preview_img = ""

# Copyright notice if desired. Defaults to
copyright = "Rinfella Pachuau © 2025"

# What is displayed in the top left corner of the website. Default is zerm.
logo_text = "UNIX"

# Link in logo. Default returns you to $BASE_URL.
logo_home_link = "/"

# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
              {url="/", name="Home"},
              {url="/tags/", name="Tags"},
              {url="/categories/", name="Categories"},
              {url="https://github.com/Rinfella/zola-ssg", name="Github", external=true},
]

# Displayed as title of drop-down menu when size of main_menu > show_menu_items.
menu_more = "show more"

# Displayed after teaser text for a blog post.
read_more = "read more"
read_other_posts = "read other posts"


# Enable math typesetting with KaTeX
enable_katex = true

# Options for disqus
disqus = { enabled=false, short_name="" }

# generate Table of Contents for all articles
# Table of Contents can be generated for individual articles
ToC = true
