name = "after-dark"
description = "A robust, elegant dark theme"
license = "MIT"
homepage = "https://github.com/getzola/after-dark"
min_version = "0.17.0"
demo = "https://getzola.github.io/after-dark/"

[extra]


[author]
name = "Rinfela Pachuau"
homepage = "https://lazara.hashnode.dev"

[original]
author =  "confusion"
homepage = "https://git.habd.as/confusion/after-dark/"
repo = "https://git.habd.as/confusion/after-dark/"
